### ISSUE TITLE
Persistir coletas em uma base de dados

### ISSUE THREAD

**Issue by sergiomario** [daniboy000/sc_aguas#3]
- [x] Definir modelo das entidades;

**Comment by andrewsmedina** [comment]
podemos criar um `command` do Django para fazer isso: https://docs.djangoproject.com/en/1.9/howto/custom-management-commands/

**Comment by sergiomario** [comment]
Hum...
@ebonet @jairojair vejam a indicação do @andrewsmedina 

Pode ser que com o 'command' não seja necessário criar um projeto separado somente para popular o banco.

**Comment by ebonet-zz** [comment]
Pode ser. Ai subimos o app no heroku e pronto.

**Comment by sergiomario** [comment]
@ebonet A gente podia aproveitar que o @andrewsmedina do time da globo comentou aqui, e subir no Tsuru em vez do heroku hahaha

**Comment by ebonet-zz** [comment]
O que for mais simples ashusah

**Comment by andrewsmedina** [comment]
o tsuru não tem uma cloud pública, acho que o melhor é usar o heroku mesmo

¯_(ツ)_/¯

**Comment by jairojair** [comment]
https://www.openshift.com é uma alternativa :)

**Comment by ebonet-zz** [comment]
to usando heroku num app flask e tem funcionado super de boa. Pelo que vi a conta free deixa criar um worker tb, que seria o cara pra fazer o fetch.

**Comment by andrewsmedina** [comment]
eu acho o heroku bem digno :)

**Comment by andrewsmedina** [comment]
outro PR com o command: https://github.com/daniboy000/sc_aguas/pull/7

**Comment by ebonet-zz** [comment]
Essa issue foi fexada mesmo? Só a criação do comando foi finalizada, a parte de persistência ainda não.

**Comment by sergiomario** [comment]
Fechei de forma errada, era somente para ter marcado a primeira tarefa.

**Comment by andrewsmedina** [comment]
@ebonet o comando já salva no banco de dados: https://github.com/daniboy000/sc_aguas/blob/master/project/aguas/management/commands/import.py#L145

**Comment by sergiomario** [comment]
Essa issue tá fechada. O command resolve o problema de persistência.

Haverá outras issues para integração contínua.

**Comment by andrewsmedina** [comment]
para rodar esse comando podemos usar o "scheduler" do heroku que é tipo um cron: https://devcenter.heroku.com/articles/scheduler
