### ISSUE TITLE
Implementação de uma API Rest

### ISSUE THREAD

**Issue by sergiomario** [daniboy000/sc_aguas#4]
- [ ] Criação de um projeto Django;
- [ ] Django Rest Framework.

**Comment by ebonet-zz** [comment]
Essa API pode ser totalmente independente do script em si. Da pra colocar o script rodando numa cron e a api só acessa o bd.

**Comment by jairojair** [comment]
@ebonet sim concordo, Projeto normal (API <-> DB). Outro projeto, script ou command para popular o bd acredito ser uma melhor forma :)

**Comment by sergiomario** [comment]
@ebonet @jairojair Gostei da ideia.

O que pensa sobre a separação @daniboy000 ??

**Comment by daniboy000** [comment]
@ebonet, @jairojair e @sergiomario, não vejo problema algum.

**Comment by andrewsmedina** [comment]
criei uma PR com o projeto django, models e a api: https://github.com/daniboy000/sc_aguas/pull/5
